### ISSUE TITLE
怎么运行

### ISSUE THREAD

**Issue by shiyao5912** [LovelyWhite/LibraryHack#1]
作者，这个要怎么运行啊，我在手机上下载了那个终端，运行命令说没有权限，但是我看你都是有页面的啊

**Comment by LovelyWhite** [comment]
自己琢磨吧，不做任何技术支持

**Comment by shiyao5912** [comment]
提供一下思路呗，只下载了压缩包，不知道干啥了！！！用了那个终端还是报错！！！
